services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: database_heyne
      POSTGRES_USER: heyne
      POSTGRES_PASSWORD: heyne123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

    # Health check for PostgreSQL - Avoid early conection attempts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heyne -d database_heyne -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  tomcat:
    image: tomcat:10.1-jdk21
    container_name: tomcat_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"
    volumes:
      - ./gestor-series-plataformes/target/gestor-series-plataformes-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: database_heyne
      DB_USER: heyne
      DB_PASSWORD: heyne123
    networks:
      - app-network

    # Health check for Tomcat - Ensure the application is up and running
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
