name: Java Continuous Integration Workflow (Docker + Apache Maven)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"
          cache: "maven"

      # Build and test the application using Maven. Also check the style of the code with Checkstyle.
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./gestor-series-plataformes

      # Check code using Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: ./gestor-series-plataformes

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./gestor-series-plataformes

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d

        # Run loops to check container health status. If healthy continue to next container.
      - name: Wait for services to be healthy
        run: |
          echo "Waiting for PostgreSQL to be healthy..."

          for i in {1..30}; do
            $STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose -f docker-compose.yml ps -q postgres))
            echo "PostgreSQL health status: $STATUS"
            if [ "$STATUS" = "healthy" ]; then
              echo "PostgreSQL is healthy!"
              break
            fi
            sleep 5
          done

          echo "Waiting for Tomcat to be healthy..."

          for i in {1..30}; do
            $STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose -f docker-compose.yml ps -q tomcat))
            echo "Tomcat health status: $STATUS"
            if [ "$STATUS" = "healthy" ]; then
              echo "Tomcat is healthy!"
              break
            fi
            sleep 2
          done
